version: "3.8"

services:
    web:
        environment:
            - APPLICATION_NAME=podcast_backend
            - DEBUG=True
            - SECRET_KEY=TESTE
            - DATABASE_NAME=postgres
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=123
        build: .
        command: bash -c "
            python manage.py makemigrations
            && python manage.py migrate
            && python manage.py collectstatic --noinput
            && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: postgres:13
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
        
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: